---
layout: post
title: What I have read, heard or seen on 2016-12-12.
author: Feodor Georgiev
published: false # set to false to start with
status: process #change to process if the file needs to be sent through knittr
draft: false
tags: R Jupyter notebooks RStudio research
---

One of the greatest blog posts I have read recently was the [How the Circle Line rogue train was caught with data] (https://blog.data.gov.sg/how-we-caught-the-circle-line-rogue-train-with-data-79405c86ab6a)

It seems like a serious effort was made to solve a real challenge. What was really impressive was the transformation of data to show where trains are between stations and to mark their direction of travel. It is also impressive that the data scientists got to blog about it and to publish the research and their code. 

Finally, what really gives me hope is the fact that nowadays the mindset around data seems to be more open than before - some 5 years ago technology and ideas were locked down and much harder to expose and reuse. Nowadays it is great that we have tools like R, [Jupyter](http://jupyter.org/), Python and various Notebooks which are used and shared by data scientists. 

Even Microsoft has made a great turn towards data open-ness. By purchasing Revolution Analytics and implementing R into SQL Server, Microsoft has gained quite some popularity in the field of data research. Here is a wonderful article on predictive analytics with SQL Server 2016: [A predictive maintenance solution template with SQL Server R Services](http://blog.revolutionanalytics.com/2016/09/r-services-maintenance.html)

This is a great article, which really makes me think that Microsoft is getting back on the right track. If you look closely in the article, you will see that there is a reference to an entire library of samples on Github, which use Microsoft's R implementation to solve real business challenges: [Machine Learning Templates with SQL Server 2016 R Services](https://github.com/Microsoft/SQL-Server-R-Services-Samples)

And finally, here is a great visualization of gas prices in Germany. It is awesome that it takes so little code and the data is so accessible: [http://flovv.github.io/Gas_price-Mapping/](http://flovv.github.io/Gas_price-Mapping/)


